import Hummingbird
import Wire

// The route collation feature: the contributor protocol, its collation key, the
// `@HummingbirdRoute` macro, and the contribution alias.

/// A route contributor. `addWireRoutes` is generated by `@HummingbirdRoute` — it owns
/// the mount point and delegates to the controller's hand-written `addRoutes`. Not
/// intended to be written by hand (the `Wire` in the name marks it generated).
public protocol HummingbirdRouteContributor {
    func addWireRoutes<Context: RequestContext>(to router: some RouterMethods<Context>)
}

extension HummingbirdKeys {
    /// Routes `@HummingbirdRoute` aliases into.
    public static let routes = CollectedKey<any HummingbirdRouteContributor>()
}

/// Makes a controller a `HummingbirdRouteContributor`, mounting its `addRoutes` under `path`
/// (`router.group(path)`). The controller keeps its natural `addRoutes(to: some
/// RouterMethods<some RequestContext>)`; the macro generates the `addWireRoutes`
/// witness. Aliases `@Contributes(to: HummingbirdKeys.routes)`, so `@Singleton
/// @HummingbirdRoute("path")` is all a controller needs.
@attached(extension, conformances: HummingbirdRouteContributor, names: named(addWireRoutes(to:)))
public macro HummingbirdRoute(_ path: String) =
    #externalMacro(module: "WireHummingbirdMacros", type: "HummingbirdRouteMacro")

/// Makes a controller a `HummingbirdRouteContributor` mounted at the router root (no group).
@attached(extension, conformances: HummingbirdRouteContributor, names: named(addWireRoutes(to:)))
public macro HummingbirdRoute() =
    #externalMacro(module: "WireHummingbirdMacros", type: "HummingbirdRouteMacro")

/// Tells Wire that `@HummingbirdRoute` aliases `@Contributes(to: HummingbirdKeys.routes)`,
/// so a controller needs only `@Singleton @HummingbirdRoute("path")` — the plugin
/// collates it without a separate `@Contributes`.
public let wireHummingbirdRouteAlias = WireAdapterAnnotationV1(
    annotation: "HummingbirdRoute",
    contributesTo: HummingbirdKeys.routes
)
