import Hummingbird
import Wire

// WireHummingbird — app-scoped route collation, context-free. `@HummingbirdRoute`
// fans controllers into a routes key as `any HummingbirdRouteContributor`; Wire emits
// a `HummingbirdComposable` conformance on the generated graph; `apply` applies the
// collated contributors to a user-owned router that stays *outside* the graph.
//
// The collation surface carries no `Context`: `HummingbirdRouteContributor`'s witness is a
// generic method, so the app's request context binds at the `apply` call, not on
// the controller. Controllers that need typed request-scoped state (auth) belong
// in WireMVC, not here.

/// A route contributor. `addWireRoutes` is generated by `@HummingbirdRoute` — it
/// owns the mount point and delegates to the controller's hand-written `addRoutes`.
/// Not intended to be written by hand (the `Wire` in the name marks it generated).
public protocol HummingbirdRouteContributor {
    func addWireRoutes<Context: RequestContext>(to router: some RouterMethods<Context>)
}

/// The collation key `@HummingbirdRoute` aliases into. `public`, so the
/// no-consumer check stays silent — the graph conformance consumes it invisibly to
/// the plugin, and an app could consume it externally — no `allowUnused` needed.
public enum HummingbirdKeys {
    public static let routes = CollectedKey<any HummingbirdRouteContributor>()
}

/// The surface the facade consumes — the generated graph conforms to this.
public protocol HummingbirdComposable {
    var routes: [any HummingbirdRouteContributor] { get }
}

/// Tells Wire to emit `extension _WireGraph: HummingbirdComposable`, mapping
/// `routes` to the routes `CollectedKey`'s product.
public let wireHummingbirdConformance = WireGraphConformanceV1(
    conformsTo: (any HummingbirdComposable).self,
    members: [.init("routes", from: HummingbirdKeys.routes)]
)

/// Tells Wire that `@HummingbirdRoute` aliases `@Contributes(to: HummingbirdKeys.routes)`,
/// so a controller needs only `@Singleton @HummingbirdRoute("path")` — the plugin
/// collates it without a separate `@Contributes`.
public let wireHummingbirdRouteAlias = WireAdapterAnnotationV1(
    annotation: "HummingbirdRoute",
    contributesTo: HummingbirdKeys.routes
)

public enum WireHummingbird {
    /// Apply the graph's collated route contributors to a user-owned router. The
    /// router's context binds each contributor's generic witness here.
    public static func apply<Context: RequestContext>(
        _ graph: some HummingbirdComposable,
        to router: some RouterMethods<Context>
    ) {
        for contributor in graph.routes {
            contributor.addWireRoutes(to: router)
        }
    }
}
