import Hummingbird
import ServiceLifecycle
import Wire

// WireHummingbird — app-scoped route collation, context-free. `@HummingbirdRoute`
// fans controllers into a routes key as `any HummingbirdRouteContributor`; Wire emits
// a `HummingbirdComposable` conformance on the generated graph; `apply` applies the
// collated contributors to a user-owned router that stays *outside* the graph.
//
// The collation surface carries no `Context`: `HummingbirdRouteContributor`'s witness is a
// generic method, so the app's request context binds at the `apply` call, not on
// the controller. Controllers that need typed request-scoped state (auth) belong
// in WireMVC, not here.

/// A route contributor. `addWireRoutes` is generated by `@HummingbirdRoute` — it
/// owns the mount point and delegates to the controller's hand-written `addRoutes`.
/// Not intended to be written by hand (the `Wire` in the name marks it generated).
public protocol HummingbirdRouteContributor {
    func addWireRoutes<Context: RequestContext>(to router: some RouterMethods<Context>)
}

/// The collation keys. `public`, so the no-consumer check stays silent — the graph
/// conformance consumes each invisibly to the plugin, and an app could consume them
/// externally — no `allowUnused` needed.
public enum HummingbirdKeys {
    /// Routes `@HummingbirdRoute` aliases into.
    public static let routes = CollectedKey<any HummingbirdRouteContributor>()
    /// App-scoped `ServiceLifecycle` services (a DB client, a connection pool) a
    /// binding `@Contributes` to run alongside the server. Context-free — `any
    /// Service` carries no request context — so it collates the way routes do.
    public static let services = CollectedKey<any Service>()
}

/// The surface the facade consumes — the generated graph conforms to this.
public protocol HummingbirdComposable {
    var routes: [any HummingbirdRouteContributor] { get }
    var services: [any Service] { get }
}

/// Tells Wire to emit `extension _WireGraph: HummingbirdComposable`, mapping each
/// member to its `CollectedKey`'s product.
public let wireHummingbirdConformance = WireGraphConformanceV1(
    conformsTo: (any HummingbirdComposable).self,
    members: [.init("routes", from: HummingbirdKeys.routes), .init("services", from: HummingbirdKeys.services)]
)

/// Tells Wire that `@HummingbirdRoute` aliases `@Contributes(to: HummingbirdKeys.routes)`,
/// so a controller needs only `@Singleton @HummingbirdRoute("path")` — the plugin
/// collates it without a separate `@Contributes`.
public let wireHummingbirdRouteAlias = WireAdapterAnnotationV1(
    annotation: "HummingbirdRoute",
    contributesTo: HummingbirdKeys.routes
)

/// Tells Wire that `@HummingbirdService` aliases `@Contributes(to: HummingbirdKeys.services)`,
/// so a service needs only `@Singleton @HummingbirdService` — the plugin collates it
/// without a separate `@Contributes`.
public let wireHummingbirdServiceAlias = WireAdapterAnnotationV1(
    annotation: "HummingbirdService",
    contributesTo: HummingbirdKeys.services
)

public enum WireHummingbird {
    /// Apply the graph's collated route contributors to a user-owned router (the
    /// router's context binds each contributor's generic witness here) and return
    /// the graph's collated `ServiceLifecycle` services to hand to
    /// `Application(services:)`. Once `@Teardown` emission lands (M4), a
    /// graph-teardown `Service` prepends here so it shuts down last.
    @discardableResult
    public static func apply<Context: RequestContext>(
        _ graph: some HummingbirdComposable,
        to router: some RouterMethods<Context>
    ) -> [any Service] {
        for contributor in graph.routes {
            contributor.addWireRoutes(to: router)
        }
        return graph.services
    }
}
