import Hummingbird
import Wire

// WireHummingbird — app-scoped route collation, context-free. Controllers
// `@Contributes` into a routes key as `any RouteContributor`; Wire emits a
// `HummingbirdComposable` conformance on the generated graph; `apply` applies the
// collated contributors to a user-owned router that stays *outside* the graph.
//
// The collation surface carries no `Context`: `RouteContributor`'s witness is a
// generic method, so the app's request context binds at the `apply` call, not on
// the controller. Controllers that need typed request-scoped state (auth) belong
// in WireMVC, not here.

/// A route contributor. `addWireRoutes` is generated by `@HummingbirdRoute` — it
/// owns the mount point and delegates to the controller's hand-written `addRoutes`.
/// Not intended to be written by hand (the `Wire` in the name marks it generated).
public protocol RouteContributor {
    func addWireRoutes<Context: RequestContext>(to router: some RouterMethods<Context>)
}

/// The collation key controllers `@Contributes(to:)`. `allowUnused` because it's
/// consumed by the generated conformance, not `@Inject`ed.
public enum HummingbirdKeys {
    public static let routes = CollectedKey<any RouteContributor>(allowUnused: true)
}

/// The surface the facade consumes — the generated graph conforms to this.
public protocol HummingbirdComposable {
    var routes: [any RouteContributor] { get }
}

/// Tells Wire to emit `extension _WireGraph: HummingbirdComposable`, mapping
/// `routes` to the routes `CollectedKey`'s product.
public let wireHummingbirdConformance = WireGraphConformanceV1(
    conformsTo: (any HummingbirdComposable).self,
    members: [.init("routes", from: HummingbirdKeys.routes)]
)

public enum WireHummingbird {
    /// Apply the graph's collated route contributors to a user-owned router. The
    /// router's context binds each contributor's generic witness here.
    public static func apply<Context: RequestContext>(
        _ graph: some HummingbirdComposable,
        to router: some RouterMethods<Context>
    ) {
        for contributor in graph.routes {
            contributor.addWireRoutes(to: router)
        }
    }
}
